### ISSUE TITLE
Não é possível fazer o build do projeto

### ISSUE THREAD

**Issue by israelfaria** [vocefiscal/vocefiscal-android#1]
Criei um ambiente de dev aqui. O projeto foi adicionado ao Eclipse Luna 4.4 com ADT. Não foi possível fazer o projeto executar o build por falta de uma referência as cores "android:textColor="@color/azul_vocefiscal".

Esta definição não foi comitada ainda, certo?

**Comment by andre-paraense** [comment]
Olá, Israel, isso mesmo, faltava commitar o colors.xml. Já está resolvido.
