### ISSUE TITLE
Remover Campinas, SP como cidade default

### ISSUE THREAD

**Issue by hsribei** [vocefiscal/vocefiscal-android#20]
Acho que isso passou batido de todo mundo porque testamos só em Campinas. Sempre via Campinas como default, mas achava que tinha pegado do GPS ou algo assim. Muitas pessoas mandando email depois falando que erraram a cidade, se dava para corrigir, etc. Erro banal mas com efeitos muito graves, precisamos corrigir com urgência. Ou pegamos a cidade do GPS, ou deixamos a seleção vazia por default para o usuário ser forçado a escolher.

**Comment by andre-paraense** [comment]
Removida - agora o usuário é forçado a selecionar e depois fica gravado o que selecionou.
