### ISSUE TITLE
Adicionar ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [vocefiscal/vocefiscal-android#25]
Seria muito bacana ter esse app no F-Droid, que é uma espécie de Google Play mas com apenas software livre: https://f-droid.org/

Aqui tem instruções de como adicioná-lo à fila de inclusão: https://f-droid.org/contribute/

Já existe um thread para sua inclusão em https://f-droid.org/forums/topic/voce-fiscal/

**Comment by dfaranha** [comment]
Olá!

Obrigado pela iniciativa, mas não faz sentido incluir essa versão do aplicativo, pois a mesma se tornou obsoleta após o TSE implantar códigos QR a partir das eleições 2016. Uma nova versão entrará em produção em alguns meses, cujo tempo de vida deverá também ser mais longo.

**Comment by pizzamaker** [comment]
Ahh entendi. Por que não atualizar esse aplicativo em vez de criar um novo repositório? Seria mais prático pro usuário, não precisar baixar um novo a cada eleição :)

**Comment by dfaranha** [comment]
Provavelmente será o caso, até porque vamos aproveitar a identidade visual e afins. Meu ponto é que essa não é a melhor hora para adicionar o aplicativo à F-Droid! :)

**Comment by pizzamaker** [comment]
@dfaranha O Você Fiscal ainda tá produzindo um aplicativo? Fiquei um pouco desapontado ao não encontrar o código-fonte do aplicativo que o projeto tá recomendando, o Apura Fácil. Transparência, kd?

**Comment by dfaranha** [comment]
Não conseguimos obter recursos para finalizar nosso próprio aplicativo, então tivemos que unir esforços com a equipe do Apura Fácil para fiscalizar a partir da base de códigos QR coletadas por eles. Estamos em contato permanente e eles já receberam diversas solicitações nesse sentido, então é possível que divulguem. Sugiro entrar em contato e engrossar o coro!

**Comment by pizzamaker** [comment]
Que pena. Mas valeu pelo toque, vou insistir lá com eles :)
