### ISSUE TITLE
Bug: app capota quando usuário bota email no form

### ISSUE THREAD

**Issue by hsribei** [vocefiscal/vocefiscal-android#5]
Passos para reproduzir:
- Tire fotos
- Preencha formulário com email
- Clique em enviar via wifi
- App capota.

**Comment by hsribei** [comment]
@andre-paraense-mobwise tem como dar uma olhada nisso pfv? Enviei reports para o GPlay, devem ter mais detalhes para debug.

**Comment by andre-paraense** [comment]
Corrigido
