### ISSUE TITLE
Alternar entre teclado querty e numerico

### ISSUE THREAD

**Issue by mstrey** [vocefiscal/vocefiscal-android#9]
Na tela onde devem ser informados os dados da seção, ao selecionar o numero da zona o teclado alterna para numérico, mas ao clicar sobre Local da votação ele não alterna para querty e não permite que o layout seja alternado manualmente.

Creio que a informação desejada neste campo seja algo como o nome da escola ou local.

**Comment by mstrey** [comment]
Alterado o inputtype do campo local_votacao_et de number para text através do pull request #10

**Comment by hsribei** [comment]
Oi @mstrey, na verdade, o campo "local de votação" consta no BU impresso, e é numérico. Valeu pela proatividade! Se quiser pegar um problema parecido e que eu acho que vai confundir muita gente, tem esse aqui: https://github.com/vocefiscal/vocefiscal-android/issues/2. Esse formulário realmente tem que ficar muito claro e simples de usar, e já tem gente reclamando desse "bug" dos 4 dígitos. Qualquer dúvida é só falar. Muito obrigado! Abraço, Helder.

**Comment by mstrey** [comment]
Blz,
Obrigado pelo comentário. vou ver se consigo resolver esse caso dos 4 digitos hoje a noite então.

valeu.

**Comment by hsribei** [comment]
Massa, valeu!
